version: '3.8'

services:
  tcc:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - GITLAB_HOST=${GITLAB_HOST}
      - HOSTNAME=${HOSTNAME}
      - OLLAMA_API=${OLLAMA_API}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_USERNAME=${WEBHOOK_USERNAME}
      - SERVICE=${SERVICE}
      - GITLAB_PROJECT_ID=${GITLAB_PROJECT_ID}
    restart: unless-stopped